name: Build LLVM 22.1 Static

on:
  push:
    paths:
      - .github/workflows/llvm.yml
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:
    inputs:
      llvmversion:
        type: string
        default: llvmorg-22.1.3
        description: Enter the llvmorg version
        required: true

permissions:
  contents: write
  actions: read

env:
  llvmversion: ${{ github.event.inputs.llvmversion || 'llvmorg-22.1.3' }}

jobs:
  windows:
    name: Build LLVM (${{ matrix.triple }})

    # Ironically, windows 11 Arm runs and builds times faster than windows-latest
    runs-on: windows-11-arm

    strategy:
      matrix:
        include:
          - arch: AArch64
            triple: aarch64-pc-windows-msvc
            vsmode: arm64

          - arch: X86
            triple: x86_64-pc-windows-msvc
            vsmode: arm64_x64

          - arch: X86
            triple: i686-pc-windows-msvc
            vsmode: arm64_x86

    steps:
      - name: Git Large Path
        run: git config --global core.longpaths true

      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout LLVM
        uses: actions/checkout@v6
        with:
          repository: llvm/llvm-project
          path: llvm
          fetch-depth: 1
          ref: ${{ env.llvmversion }}

      - name: Install Ninja
        run: pip install ninja

      - name: Build LLVM
        working-directory: llvm
        shell: cmd
        run: |
          for /f "usebackq tokens=*" %%i in (`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationPath`) do (
            set "VS_PATH=%%i"
          )

          call "%VS_PATH%\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.vsmode }}

          :: Build
          cmake -G Ninja -S llvm -B build ^
            -DCMAKE_BUILD_TYPE=Release ^
            -DLLVM_DEFAULT_TARGET_TRIPLE=${{ matrix.triple }} ^
            -DLLVM_TARGETS_TO_BUILD="${{ matrix.arch }}" ^
            -DLLVM_BUILD_TOOLS=OFF ^
            -DLLVM_INCLUDE_TESTS=OFF ^
            -DLLVM_ENABLE_PLUGINS=OFF ^
            -DCMAKE_INSTALL_PREFIX=install

          ninja -C build llvm-config
          ninja -C build install

          if not exist "install\bin\llvm-config.exe" (
            copy "build\bin\llvm-config.exe" "install\bin\"
          )

      - name: Tar
        run: |
          tar -czvf llvm-static-${{ matrix.triple }}.tar.gz `
            -C llvm/install lib include bin

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: llvm-static-${{ matrix.triple }}
          path: llvm-static-${{ matrix.triple }}.tar.gz
          archive: true

  macos:
    name: Build LLVM (${{ matrix.triple }})

    strategy:
      matrix:
        include:
          # MacOS
          - arch: AArch64
            os: macos-26
            triple: arm64-apple-darwin

          - arch: X86
            os: macos-26-intel
            triple: x86_64-apple-darwin

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout LLVM
        uses: actions/checkout@v6
        with:
          repository: llvm/llvm-project
          path: llvm
          fetch-depth: 1
          ref: ${{ env.llvmversion }}

      - name: Build LLVM
        working-directory: llvm
        run: |
          # Build
          cmake -G Ninja -S llvm -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_DEFAULT_TARGET_TRIPLE=${{ matrix.triple }} \
            -DLLVM_TARGETS_TO_BUILD="${{ matrix.arch }}" \
            -DLLVM_BUILD_TOOLS=OFF \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_ENABLE_PLUGINS=OFF \
            -DCMAKE_INSTALL_PREFIX=install

          ninja -C build llvm-config
          ninja -C build install

          mkdir -p install/bin
          cp build/bin/llvm-config* install/bin/

      - name: Tar
        run: |
          tar -czvf llvm-static-${{ matrix.triple }}.tar.gz \
            -C llvm/install lib include bin

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: llvm-static-${{ matrix.triple }}
          path: llvm-static-${{ matrix.triple }}.tar.gz
          archive: true

  linux:
    name: Build LLVM (${{ matrix.triple }})

    strategy:
      fail-fast: false
      matrix:
        include:
          # Arm64
          - arch: AArch64
            install: clang lld libc6-dev-arm64-cross crossbuild-essential-arm64
              gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu
            triple: aarch64-linux-gnu
            dpkg: sudo dpkg --add-architecture arm64
            script: |
              sudo apt-get install -y libc6:arm64 libgcc1:arm64

          # x86_64 (x64)
          - arch: X86
            install: clang lld
            triple: x86_64-linux-gnu
            sysroot: ""

          # i686 (x86 32-bit)
          - arch: X86
            install: clang lld gcc-multilib g++-multilib
            triple: i686-linux-gnu
            flags: -DCMAKE_C_FLAGS="-m32" -DCMAKE_CXX_FLAGS="-m32"
            sysroot: ""

          # LoongArch64
          # - arch: LoongArch
          #   install: clang lld libc6-dev-loong64-cross
          #   triple: loongarch64-linux-gnu
          #   script: |
          #     sudo dpkg --add-architecture arm64
          #     sudo apt-get update
          #     sudo apt-get install -y libc6:arm64 libgcc1:arm64

          # ARMv7 (HF)
          - arch: ARM
            install: clang lld libc6-dev-armhf-cross gcc-arm-linux-gnueabihf
              binutils-arm-linux-gnueabihf
            triple: arm-linux-gnueabihf
            dpkg: sudo dpkg --add-architecture armhf
            script: |
              sudo apt-get install -y libc6:armhf libgcc1:armhf

          # RISCV64
          - arch: RISCV
            install: clang lld libc6-dev-riscv64-cross gcc-riscv64-linux-gnu
              binutils-riscv64-linux-gnu
            triple: riscv64-linux-gnu
            dpkg: sudo dpkg --add-architecture riscv64
            script: |
              sudo apt-get install -y libc6:riscv64 libgcc1:riscv64

          # PowerPC
          - arch: PowerPC
            install: clang lld libc6-dev-ppc64el-cross gcc-powerpc64le-linux-gnu
              binutils-powerpc64le-linux-gnu
            triple: powerpc64le-linux-gnu
            dpkg: sudo dpkg --add-architecture ppc64el
            script: |
              sudo apt-get install -y libc6:ppc64el libgcc1:ppc64el

          # MIPS64
          - arch: Mips
            install: clang lld libc6-dev-mips64el-cross gcc-mips64el-linux-gnuabi64
              binutils-mips64el-linux-gnuabi64
            triple: mips64el-linux-gnu
            dpkg: sudo dpkg --add-architecture mips64el
            script: |
              sudo apt-get install -y libc6:mips64el libgcc1:mips64el

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout LLVM
        uses: actions/checkout@v6
        with:
          repository: llvm/llvm-project
          path: llvm
          fetch-depth: 1
          ref: ${{ env.llvmversion }}

      - name: Install Dependencies
        run: |
          sudo apt-get install -y lld ${{ matrix.install }}

          ${{ matrix.dpkg }}

          # 1. Update existing sources to only look for amd64
          sudo sed -i 's/deb http/deb [arch=amd64] http/g' /etc/apt/sources.list
          sudo sed -i 's/deb htp/deb [arch=amd64] htp/g' /etc/apt/sources.list

          sudo find /etc/apt/sources.list.d/ -type f -name "*.list" -exec sed -i 's/deb http/deb [arch=amd64] http/g' {} +

          cat <<EOF | sudo tee /etc/apt/sources.list.d/arm-ports.list
          deb [arch=arm64,armhf,riscv64,ppc64el,mips64el] http://ports.ubuntu.com/ubuntu-ports noble main restricted universe multiverse
          deb [arch=arm64,armhf,riscv64,ppc64el,mips64el] http://ports.ubuntu.com/ubuntu-ports noble-updates main restricted universe multiverse
          deb [arch=arm64,armhf,riscv64,ppc64el,mips64el] http://ports.ubuntu.com/ubuntu-ports noble-security main restricted universe multiverse
          EOF

          sudo apt-get update
          ${{ matrix.script }}

      - name: Build LLVM
        working-directory: llvm
        run: |
          export CC=clang
          export CXX=clang++

          # LLVM Host
          cmake -G Ninja -S llvm -B build_native \
            -DLLVM_TARGETS_TO_BUILD="Native" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_USE_LINKER=lld
          ninja -C build_native llvm-tblgen

          rm -rf .git
          cp $(pwd)/build_native/bin/llvm-tblgen $(pwd)/native-llvm-tblgen
          rm -rf build_native

          # Cross Build
          cmake -G Ninja -S llvm -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_C_FLAGS="--target=${{ matrix.triple }} -fuse-ld=lld --sysroot=/usr/${{ matrix.sysroot || matrix.triple }}" \
            -DCMAKE_CXX_FLAGS="--target=${{ matrix.triple }} -fuse-ld=lld --sysroot=/usr/${{ matrix.sysroot || matrix.triple }}" \
            -DLLVM_TABLEGEN=$(pwd)/native-llvm-tblgen \
            -DLLVM_DEFAULT_TARGET_TRIPLE=${{ matrix.triple }} \
            -DLLVM_TARGETS_TO_BUILD="${{ matrix.arch }}" \
            -DLLVM_BUILD_STATIC=ON \
            -DLLVM_BUILD_TOOLS=OFF \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_ENABLE_PLUGINS=OFF \
            -DCMAKE_INSTALL_PREFIX=install \
            -DLLVM_USE_LINKER=lld ${{ matrix.flags }} \
            -DLLVM_ENABLE_ZLIB=OFF \
            -DLLVM_ENABLE_ZSTD=OFF \
            -DLLVM_ENABLE_TERMINFO=OFF \
            -DLLVM_STATIC_LINK_CXX_STDLIB=ON

          ninja -C build llvm-config 
          ninja -C build install

          mkdir -p install/bin
          cp build/bin/llvm-config* install/bin/

      - name: Tar
        run: |
          tar -czvf llvm-static-${{ matrix.triple }}.tar.gz \
            -C llvm/install lib include bin

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: llvm-static-${{ matrix.triple }}
          path: llvm-static-${{ matrix.triple }}.tar.gz
          archive: true

  release-llvm:
    name: Release LLVM

    runs-on: ubuntu-latest

    needs: [ windows, macos, linux ]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download all artifacts
        run: gh run download ${{ github.run_id }} --dir release
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Generate timestamp
        id: time
        run: echo "time=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: Release Artifacts
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ env.llvmversion }}-${{ steps.time.outputs.time }}
          body: |
            # LLVM Build (${{ env.llvmversion }})
            Uploaded at : ${{ steps.time.outputs.time }}

            This is an autogenerated build of LLVM meant for static compilation of LLVM to be used
            in SaVM Projects.
          files: release/**/*.tar.gz
