name: Build LLVM 22.1 Static

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  linux:
    name: Build LLVM (${{ matrix.triple }})

    strategy:
      matrix:
        include:
          # Arm64
          - arch: AArch64
            install: gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
            gcc: aarch64-linux-gnu-gcc
            gpp: aarch64-linux-gnu-g++
            triple: aarch64-linux-gnu
            linker: -DLLVM_USE_LINKER=lld

          # x86_64 (x64)
          - arch: X86
            install: gcc g++
            gcc: gcc
            gpp: g++
            triple: x86_64-linux-gnu
            linker: -DLLVM_USE_LINKER=lld

          # i686 (x86 32-bit)
          - arch: X86
            install: gcc-multilib g++-multilib
            gcc: gcc
            gpp: g++
            triple: i686-linux-gnu
            linker: -DLLVM_USE_LINKER=lld

          # LoongArch64 (GCC 13)
          - arch: LoongArch
            install: gcc-13-loongarch64-linux-gnu g++-13-loongarch64-linux-gnu
            gcc: loongarch64-linux-gnu-gcc-13
            gpp: loongarch64-linux-gnu-g++-13
            triple: loongarch64-linux-gnu

          # ARMv7 (HF)
          - arch: ARM
            install: gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
            gcc: arm-linux-gnueabihf-gcc
            gpp: arm-linux-gnueabihf-g++
            triple: arm-linux-gnueabihf
            linker: -DLLVM_USE_LINKER=lld


    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkout LLVM
        uses: actions/checkout@v6
        with:
          repository: llvm/llvm-project
          path: llvm
          fetch-depth: 1
          ref: llvmorg-22.1.3

      - name: Install Dependencies
        run: |
          sudo apt-get install -y lld ${{ matrix.install }}

      - name: Build LLVM
        working-directory: llvm
        run: |
          # LLVM Host
          cmake -G Ninja -S llvm -B build_native \
            -DLLVM_TARGETS_TO_BUILD="X86" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_USE_LINKER=lld
          ninja -C build_native llvm-tblgen

          rm -rf .git
          cp $(pwd)/build_native/bin/llvm-tblgen $(pwd)/native-llvm-tblgen
          cp $(pwd)/build_native/bin/llvm-strip $(pwd)/native-llvm-strip
          rm -rf build_native

          # Cross Build
          cmake -G Ninja -S llvm -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_C_COMPILER=${{ matrix.gcc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.gpp }} \
            -DLLVM_TABLEGEN=$(pwd)/native-llvm-tblgen \
            -DLLVM_DEFAULT_TARGET_TRIPLE=${{ matrix.triple }} \
            -DLLVM_TARGETS_TO_BUILD="${{ matrix.arch }}" \
            -DLLVM_BUILD_STATIC=ON \
            -DLLVM_BUILD_TOOLS=OFF \
            -DLLVM_INCLUDE_TESTS=OFF \
            -DLLVM_ENABLE_PLUGINS=OFF ${{ matrix.linker }}

          ninja -C build
          find build/bin -type f -executable -exec ./native-llvm-strip {} +